name: Done
run-name: Post-deploy
on:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Invalidate cache
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ZONE_ID: ${{ secrets.CLOUDFLARE_ZONE_ID }}
        run: |
          curl --request POST \
            --url "https://api.cloudflare.com/client/v4/zones/$CLOUDFLARE_ZONE_ID/purge_cache" \
            --header "authorization: Bearer $CLOUDFLARE_API_TOKEN" \
            --header 'content-type: application/json' \
            --data '{"purge_everything": true}'
          echo Done.
